development:
  adapter: postgresql
  database: db/data.sqlite3
  pool: 5
  timeout: 5000

test:
  # adapter: sqlite3
  # host: localhost
  # database: db/test.sqlite3
  # pool: 5
  # timeout: 5000
  adapter: postgresql
  host: localhost
  # username: root
  database: fb_scrape_dev
